raw_data:
  input_url: "https://datascientest-mlops.s3.eu-west-1.amazonaws.com/mlops_dvc_fr/raw.csv"
  output_folder: "data/raw_data"

preprocess_data:
  input_folder: "./data/raw_data"
  input_filename: "raw.csv"
  output_folder: "./data/processed_data"
  drop_col : ['date']
  target_col : "silica_concentrate"
  test_size: 0.2
  random_state: 42

normalize_data:
  input_folder: "./data/processed_data"
  output_folder: "./data/processed_data"
  input_filenames:
    - "X_train.csv"
    - "X_test.csv"

  
gridsearch:
  input_folder: "./data/processed_data"
  x_train_file: "X_train_scaled.csv"
  x_test_file: "X_test_scaled.csv"
  y_train_file: "y_train.csv"
  y_test_file: "y_test.csv"
  output_folder: "./models"
  output_filename: "best_params.pkl"

train_model:
  input_folder: "./data/processed_data"
  x_train_file: "X_train_scaled.csv"
  y_train_file: "y_train.csv"
  output_folder: "./models"
  output_filename: "trained_model.pkl"

evaluate_model:
  input_folder: "./data/processed_data"
  x_test_file: "X_test_scaled.csv"
  y_test_file: "y_test.csv"
  model_file: "./models/trained_model.pkl"
  predictions_file: "./data/predictions.csv"
  metrics_folder: "./metrics"
  metrics_file: "scores.json"